name: Start Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        run: |
          sudo apt update
          sudo apt install openjdk-21-jdk -y

      - name: Check files
        run: ls -la

      - name: Install playit
        run: |
          curl -L https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -o playit
          chmod +x playit

      - name: Start playit
        run: |
          nohup ./playit &

      - name: Start Server (timed)
        run: |
          timeout 5m java -Xmx2G -Xms1G -jar paper-1.21.11-130.jar nogui
